development:
  adapter: postgis
  encoding: unicode
  postgis_extension: postgis      # default is postgis
  schema_search_path: public,postgis
  database: fly_berry_development
  pool: 5
  username: <%=  ENV['database_username'] %>
  password: <%= ENV['database_password'] %>

test:
  adapter: postgresql
  encoding: unicode
  database: fly_berry_test
  pool: 5
  username: <%=  ENV['database_username'] %>
  password: <%= ENV['database_password'] %>
production:
  adapter: postgresql
  encoding: unicode
  database: fly_berry_production
  pool: 5
  username: <%=  ENV['database_username'] %>
  password: <%= ENV['database_password'] %>